(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.PadelScoring=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const POINTS=['0','15','30','40'];
  const clone=o=>JSON.parse(JSON.stringify(o));
  function freshScore(){return{blueGames:0,redGames:0,bluePoints:0,redPoints:0,tiebreak:false,complete:false,winner:null,serverTeam:'blue',history:[],startedAt:new Date().toISOString()};}
  function label(a,b,t){if(t)return String(a);if(a<=3&&b<=3)return POINTS[a];if(a===b)return'40';return a>b?'AD':'40';}
  function display(s){return{bluePoints:label(s.bluePoints,s.redPoints,s.tiebreak),redPoints:label(s.redPoints,s.bluePoints,s.tiebreak)};}
  function addPoint(state,team){if(state.complete)return clone(state);const s=clone(state);s.history.push(clone({...s,history:[]}));team==='blue'?s.bluePoints++:s.redPoints++;const own=team==='blue'?'bluePoints':'redPoints',opp=team==='blue'?'redPoints':'bluePoints';const game=s.tiebreak?(s[own]>=7&&s[own]-s[opp]>=2):(s[own]>=4&&s[own]-s[opp]>=2);if(game){team==='blue'?s.blueGames++:s.redGames++;s.bluePoints=0;s.redPoints=0;if(s.tiebreak){s.complete=true;s.winner=team;}else{const a=team==='blue'?s.blueGames:s.redGames,b=team==='blue'?s.redGames:s.blueGames;if(a>=6&&a-b>=2){s.complete=true;s.winner=team;}else if(s.blueGames===6&&s.redGames===6)s.tiebreak=true;}}if(!s.tiebreak&&s.bluePoints===s.redPoints&&s.bluePoints>3){s.bluePoints=3;s.redPoints=3;}return s;}
  function undo(state){if(!state.history?.length)return clone(state);const h=state.history.slice(),p=h.pop();p.history=h;return p;}
  function switchServer(state){const s=clone(state);s.serverTeam=s.serverTeam==='blue'?'red':'blue';return s;}
  function completedPayload(s){if(!s.complete)throw new Error('De set is nog niet klaar.');return{blue_games:s.blueGames,red_games:s.redGames,point_snapshot:{blue:'0',red:'0',tiebreak:s.tiebreak},set_completed:true,timed_out:false,winner_team:s.winner};}
  function timeOverPayload(s){const d=display(s);return{blue_games:s.blueGames,red_games:s.redGames,point_snapshot:{blue:d.bluePoints,red:d.redPoints,tiebreak:s.tiebreak},set_completed:false,timed_out:true,winner_team:null};}
  function awardedPoints(m,team){const g=team==='blue'?m.blue_games:m.red_games;return g+(m.set_completed&&m.winner_team===team?3:0);}
  function aggregate(players,matches){const map=new Map(players.map(p=>[p.id,{id:p.id,name:p.display_name||p.username,played:0,setsWon:0,setsLost:0,gamesWon:0,gamesLost:0,points:0,wins:0}]));for(const m of matches.filter(x=>x.status==='finished'&&!x.deleted_at)){const blue=[m.blue_player_1,m.blue_player_2].filter(Boolean),red=[m.red_player_1,m.red_player_2].filter(Boolean);for(const id of blue){const r=map.get(id);if(!r)continue;r.played++;r.gamesWon+=m.blue_games;r.gamesLost+=m.red_games;r.points+=awardedPoints(m,'blue');if(m.set_completed){if(m.winner_team==='blue'){r.setsWon++;r.wins++;}else r.setsLost++;}}for(const id of red){const r=map.get(id);if(!r)continue;r.played++;r.gamesWon+=m.red_games;r.gamesLost+=m.blue_games;r.points+=awardedPoints(m,'red');if(m.set_completed){if(m.winner_team==='red'){r.setsWon++;r.wins++;}else r.setsLost++;}}}return[...map.values()].map(r=>({...r,gameDiff:r.gamesWon-r.gamesLost,winPct:r.played?Math.round(r.wins/r.played*100):0})).sort((a,b)=>b.points-a.points||b.setsWon-a.setsWon||b.gameDiff-a.gameDiff||b.gamesWon-a.gamesWon||a.name.localeCompare(b.name,'nl'));}
  return{freshScore,display,addPoint,undo,switchServer,completedPayload,timeOverPayload,awardedPoints,aggregate};
});
